### ISSUE TITLE
Memory leaks in time-dependent problems

### ISSUE THREAD

**Issue by Diego-dO** [multiphenics/multiphenicsx#13] opened 2023-05-24 15:54 UTC
Hello,

I am experiencing memory leaks when using multiphenicsx to solve time-dependent problems.

I am attaching below a (maybe not so minimal) example for a diffusion-reaction problem with 3 components using multiphenicsx and the same example using directly mixed elements with dolfinx. The memory loss over the timestep iteration according to memory_profiler (https://pypi.org/project/memory-profiler/) can be seen in this figure:

<p align="center">
  <img width="400" height="300" src="https://github.com/multiphenics/multiphenicsx/assets/113597011/53758fe5-8f0e-49b1-9900-3ca72ca9a7a2">
</p>

Investigating a bit further, the memory increases in some instances when calling multiphenicsx.fem.petsc.assemble_vector_block and does not seem to be (fully?) freed afterwards.

Initially I was running the code in a container with version 0.6.0 of dolfinx and ed65a2e9 of multiphenicsx but I get the same behaviour with the nightly version of the dolfinx container and the latest multiphenicsx version. I have noticed there are some mentions in recent commits about changes in PETSc garbage collection so I am guessing it could be related to that.

[Test case with multiphenicsx](https://github.com/multiphenics/multiphenicsx/files/11556449/test_diffusionReaction_block.txt)
[Test case with dolfinx MixedElement](https://github.com/multiphenics/multiphenicsx/files/11556451/test_diffusionReaction_mixed.txt)

**Comment by francesco-ballarin** [comment] 2023-05-25 08:18
Thanks @Diego-dO for the bug report. This is definitely related to changes in PETSc garbage collection.

To help me reproduce, can you help me by creating a custom version of tutorial 02, in which you add a (fake) time loop, and verify if the issue is also present there?

**Comment by francesco-ballarin** [comment] 2023-05-26 08:57
OK thanks. What `mprof` commands did you use to save the data and create the plot?

**Comment by Diego-dO** [comment] 2023-05-26 09:11
To do the profiling I use `mprof run <script.py>`, this saves a `mprofile_{YYYYMMDDHHMMSS}.dat` file with the memory profiling that can later be plotted with the following script:

```{python3}
import numpy as np
import matplotlib.pyplot as plt

file_dfx = "mprofile_YYYYMMDDHHMMSS.dat"
file_mpx = "mprofile_yyyymmddhhmmss.dat"

data_dfx = np.loadtxt(file_dfx , skiprows=1, usecols=range(1,3))[:-1,:]
data_mpx = np.loadtxt(file_mpx , skiprows=1, usecols=range(1,3))[:-1,:]

time_dfx = (data_dfx[:,1] - data_dfx[0,1])
time_mpx = (data_mpx[:,1] - data_mpx[0,1])

plt.plot(time_dfx, data_dfx[:,0], label="dolfinx assemble")
plt.plot(time_mpx, data_mpx[:,0], label="multiphenicsx assemble")

plt.ylabel("Memory [MB]")
plt.xlabel("Time [s]")
plt.legend()
plt.savefig("memory_comparison.png")
```

**Comment by francesco-ballarin** [comment] 2023-05-27 12:38
OK, thanks @Diego-dO. I'll look into this, but I'll probably need 10 days or so to do that, because I am currently travelling.

**Comment by francesco-ballarin** [comment] 2023-06-08 08:38
Hi @Diego-dO ,
can you try the branch https://github.com/multiphenics/multiphenicsx/tree/local_submat_destroy and verify that it solves the memory leak for both tutorial 02 and your application? If possible, post updated images of the memory profiler for future reference.

**Comment by Diego-dO** [comment] 2023-06-08 14:20
Hello @francesco-ballarin ,

Thanks a lot for the fast action, I have run again the tests and it seems that the memory leaks are indeed solved with the latest changes. As suggested, I attach below the relevant figures with the lastest commit.

<p align="center">
<img width="400" height="300" src="https://github.com/multiphenics/multiphenicsx/assets/113597011/b1e7c207-640c-4659-8c45-acbcad06749c">
<img width="400" height="300" src="https://github.com/multiphenics/multiphenicsx/assets/113597011/32993c8e-5450-45d7-85fe-d3a7794583e4">
</p>

The issue can now be closed, thanks again.

**Comment by francesco-ballarin** [comment] 2023-06-08 14:26
Great, thanks very much for the bug report. I have merged to main, and thus I'll close this issue.

**Closed by francesco-ballarin** 2023-06-08 14:26 UTC
