### ISSUE TITLE
Error on running tutorial problem on eigenvalue

### ISSUE THREAD

**Issue by davidbhatt** [multiphenics/multiphenicsx#31] opened 2024-09-18 14:23 UTC
Hello everyone,
I am trying to run the tutorial problem using multiphenicsx and dolfinx 0.8.0.
https://github.com/multiphenics/multiphenicsx/blob/main/tutorials/04_eigenvalue_problems/tutorial_eigenvalue_laplacian.ipynb
on my machine
However when I run, I am getting the following assertion error:
r=-2.46... is not positive. 
I have tried with Approach1 and Approach2 . both has given me negative eigenvalue.
why the algorithm should give negative values?
Anything wrong is happening. 
Any help is appreciated
Thank You

**Comment by francesco-ballarin** [comment] 2024-09-18 16:28
Hi,
is it possible that your installation of PETSc does not have mumps? 
More in general, how did you install FEniCSx?

multiphenicsx is tested against dolfinx 0.8.0 every night (see https://github.com/multiphenics/multiphenicsx/actions/runs/10914944003/job/30293890009 for the most recent run), so I am quite sure that the issue isn't in multiphenicsx itself.

**Comment by davidbhatt** [comment] 2024-09-19 09:16
Thanks for your reply.
I have installed FEniCSx via aptitude manager
add-apt-repository ppa:fenics-packages/fenics
apt update
apt install fenicsx
The petsc version 3.15  is installed automatically by fenicsx package.
How can I check if my petsc has mumps installed in it?
what do you suggest to fix this issue?
Thank You

**Comment by francesco-ballarin** [comment] 2024-09-19 11:44
which ubuntu version do you have?

**Comment by davidbhatt** [comment] 2024-09-19 12:25
> which ubuntu version do you have?

I have Ubuntu 22.04.5 LTS  jammy

**Comment by francesco-ballarin** [comment] 2024-09-19 16:21
I cannot replicate this in a clean `ubuntu:22.04` docker image, with matching PETSc and dolfinx versions. I can't help much further unless you are able to send me a dockerfile that replicates you environment and the issue you have.

**Comment by francesco-ballarin** [comment] 2024-09-23 11:39
Closing for now, will reopen once you provide a minimal example to reproduce.

**Closed by francesco-ballarin** 2024-09-23 11:39 UTC

**Comment by davidbhatt** [comment] 2024-10-15 23:16
Thanks for your help. In order to reproduce the error, I created a docker using dolfinx v0.8.0 official docker. I tested on the same machine and it was giving the same error. However when I tested on another machine, it worked perfectly fine.
I could not figure out what is wrong with the machine. But at least the problem disappears. So I am done. Thank You
